# Practical-I

a.	Accept a number and print whether it is even or odd

In [57]:
n=int(input('Enter a number:'))
if n%2==0:
    print(n,'is even')
else:
    print(n,'is odd')

Enter a number:4
4 is even


b.	Accept n numbers and print their mean and variance

In [25]:
n=int(input('enter a size of list:'))
num=[]
for i in range(n):
    y=input('enter n numbers:')
    num.append(y)
print(num)
sx=sxx=0
t=0
for i in num:
    sx=sx+int(i)
    sxx=sxx+int(i)*int(i)
    t=t+1
mean=sx/t
var=sxx/t-mean**2
print(round(mean,2),'is the mean of given list and',round(var,3),'is the variance of given list')


enter a size of list:3
enter n numbers:4
enter n numbers:6
enter n numbers:3
['4', '6', '3']
4.33 is the mean of given list and 1.556 is the variance of given list


	c.Accept a number and print its factorial

In [28]:
n=int(input('Enter a number:'))
f=1
for i in range(1,n+1):
    f=f*i
print(f)

Enter a number:5
120


d.	Accept a number and print whether it is prime of not. Extend the programme to list down the prime number between 1 and 100 and compute mean of the same.

In [45]:
for Number in range (1, 101):
    count=0
    for i in range(2,Number//2+1):
        if Number%i==0:
            count=count+1
            
            break
    if(count==0 and Number!=1):
        print('%d'%Number,end=' ')
        

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

e.	Accept two related numeric data series and print mean and variance of each series, covariance and correlation between them.     

In [72]:
n1=int(input('enter a size of list:'))

x=[]
for i in range(n1):
    y=input('enter n numbers:')
    x.append(y)
print(x)

y=[]
for i in range(n1):
    z=input('enter n numbers:')
    y.append(z)
print(x)
sx=sxx=0
t=0
for i in x:
    sx=sx+int(i)
    sxx=sxx+int(i)*int(i)
    t=t+1
mx=sx/t
var1=sxx/t-mx**2
print(round(mx,2),'is the mean of list x and',round(var1,3),'is the variance of given list')
sy=syy=0
t=0
for i in y:
    sy=sy+int(i)
    syy=syy+int(i)*int(i)
    t=t+1
my=sy/t
var2=syy/t-my**2
print(round(my,2),'is the mean of list y and',round(var2,3),'is the variance of given list')

sxy=0
for i in range(1,n2):
    sxy=sxy+int(x[i])*int(y[i])
cov=sxy/t-mx*my
cor=cov/(var1*var2)**2
print(round(cov,3),'is the cov of lists',round(cor,3),'is the correlation of two list')

enter a size of list:3
enter n numbers:2
enter n numbers:5
enter n numbers:7
['2', '5', '7']
enter n numbers:6
enter n numbers:1
enter n numbers:2
['2', '5', '7']
4.67 is the mean of list x and 4.222 is the variance of given list
3.0 is the mean of list y and 4.667 is the variance of given list
-7.666666666666667 is the cov of lists -0.02 is the correlation of two list


f.	To generate random number from U(0,1) distribution using Congruential Random Number Generator

In [84]:
m=16
a=9
b=5
n=10
y=[]
i=1
while i<=m:
    y=(a*i+b)%m
    i=i+1
    print(y,end=' ')


14 7 0 9 2 11 4 13 6 15 8 1 10 3 12 5 

g.	To generate random number from Binomial, Poisson, Hypergeometric, Negative Binomial, Multinomial distributions using uniform random numbers

In [145]:
#Binomial

import numpy as np
p=0.9
n=5
m=10
x=np.zeros(m)
for i in range(n):
    for j in range(m):
        u=np.random.rand(1)
        if u<=p:
            x[j]=x[j]+1
print(x)        


[5. 4. 4. 5. 4. 4. 5. 5. 5. 5.]


In [135]:
#poisson
l=3
n=10
x=np.zeros(n)
y=0
for i in range(n):
    p=1
    y=-1
    while p>np.exp(-l):
        u=np.random.rand(1)
        p=p*u
        y=y+1
    x[i]=y
print(x)

[3. 2. 3. 1. 0. 6. 2. 2. 2. 2.]


In [178]:
#hypergeometric
m=10
M=8
N=30
n=10

x=np.zeros(n)
y=0
i=1
for j in range(m):
    for i in range(n):
        u=np.random.rand(1)
        while u<=((M-y)/(N-i+1)):
            x[i]=x[i]+1
            i=i+1
print(x)
        

IndexError: index 10 is out of bounds for axis 0 with size 10

In [166]:
import math as m

p=0.6
n=10
r=2
x=np.zeros(n)
for j in range(n):
    for i in range(r):
        u=np.random.rand(1)
        x[j]=m.floor(np.log(u)/np.log(1-p))
        x[j]=x[j]+1
        i=i+1
print(x)

[1. 1. 2. 4. 3. 1. 1. 2. 3. 3.]
